"""
finRAG 摘要索引器 — 将 _ai_summaries.md 的摘要chunk写入Qdrant + 重建BM25
在 generate_summaries.py 之后运行

用法: python scripts/index_summaries.py
"""

import json, logging, re, sys, time, gc, uuid
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
logger = logging.getLogger("index_summaries")

BASE_DIR = Path(__file__).resolve().parents[1]
PARSED_DIR = BASE_DIR / "data" / "parsed"
SUMMARIES_FILE = PARSED_DIR / "_ai_summaries.md"


def main():
    if not SUMMARIES_FILE.exists():
        logger.error(f"❌ {SUMMARIES_FILE} 不存在，请先运行 generate_summaries.py")
        return
    
    sys.path.insert(0, str(BASE_DIR))
    from scripts.ingestion_v2 import Config, EmbeddingEngine, QdrantIndexer, ParentChunk, ChildChunk
    from scripts.retriever import HybridRetriever
    
    cfg = Config()
    
    # 1. Parse the summaries file into chunks
    text = SUMMARIES_FILE.read_text(encoding="utf-8")
    
    # Split by ## sections
    chunks = []
    current_section = None
    current_lines = []
    
    for line in text.split("\n"):
        if line.startswith("## "):
            if current_section and current_lines:
                body = "\n".join(current_lines).strip()
                if body:
                    chunks.append({
                        "source_file": current_section,
                        "text": body,
                    })
            current_section = line[3:].strip()
            current_lines = []
        elif line.startswith("---") or line.startswith("# ") or line.startswith("_生成"):
            continue
        else:
            current_lines.append(line)
    
    if current_section and current_lines:
        body = "\n".join(current_lines).strip()
        if body:
            chunks.append({
                "source_file": current_section,
                "text": body,
            })
    
    logger.info(f"解析到 {len(chunks)} 个摘要chunk")
    
    if not chunks:
        logger.warning("⚠️ 没有可索引的摘要")
        return
    
    # 2. Embed and index
    embedder = EmbeddingEngine(cfg)
    indexer = QdrantIndexer(cfg)
    indexer.ensure_collection(force_recreate=False)
    
    # Build ParentChunks
    parent_chunks = []
    for idx, c in enumerate(chunks):
        uid = str(uuid.uuid4())
        pc = ParentChunk(
            id=uid,
            text=c["text"],
            char_count=len(c["text"]),
            index=idx,
            has_table=False,
            section="AI Summary",
            table_summary="",
            page=1,
        )
        child = ChildChunk(
            id=str(uuid.uuid4()),
            text=c["text"],
            char_count=len(c["text"]),
            index=0,
            parent_id=uid,
            has_table=False,
            section="AI Summary",
            table_summary="",
            page=1,
            search_text=c["text"],
        )
        pc.children = [child]
        parent_chunks.append(pc)
    
    # Index using the document-level method
    metadata = {
        "company": "",
        "year": "2025",
        "doc_type": "AI摘要",
        "source": "Generated by LLM",
    }
    
    total_parents = indexer.index_document(metadata, parent_chunks, embedder)
    logger.info(f"✅ 已写入 {total_parents} 个摘要父块")
    
    indexer.close()
    del embedder, indexer
    gc.collect()
    
    # 3. Rebuild BM25 to include summary chunks
    logger.info("\n⏳ 重建BM25索引...")
    retriever = HybridRetriever(cfg)
    retriever.build_bm25_index()
    logger.info("✅ BM25索引重建完成")
    
    # Verify
    from qdrant_client import QdrantClient
    client = QdrantClient(path=str(cfg.QDRANT_DB_PATH))
    count = client.count(cfg.QDRANT_COLLECTION)
    logger.info(f"📊 Qdrant总向量数: {count.count}")


if __name__ == "__main__":
    main()
